### ISSUE TITLE
可否移除冗余依赖

### ISSUE THREAD

**Issue by lococo--0** [fisker/fis3-optimizer-imagemin#1]
如果只用默认配置的话很多依赖都无法用上，而这些依赖的安装速度极慢，能否缩减依赖到默认配置，当用户需要用其他的依赖的时候再让用户自己安装

**Comment by fisker** [comment]
据我所知 除非调用的时候再调用npm执行安装 应该没有别的办法 但这些插件平常开发中应该都会用到，先装后装并没有什么区别。

gulp-imagemin 安装的时候也会安装默认的插件

或者你有别的什么点子可以pull request

**Comment by lococo--0** [comment]
诶？因为我看到你的default config里面只会用到`pngquant`, `jpegtran `, `mozjpeg `, `gifsicle`, `webp`, `svgo`这6个plugin，但是在依赖里面却有不止6个插件。

例如，像你默认用`pngquant`，那`imagemin-pngcrush`这个依赖能否去掉。
再例如`imagemin-zopfli`等等。

主要有些插件的post-install慢到哭

**Comment by lococo--0** [comment]
诶？我发现我理解错了，你并没有对任何ext有默认配置

**Comment by fisker** [comment]
预装是为了配置的时候可以直接调用

临时解决方法。
你可以自己fork个 删掉不要的依赖 ` npm i -g .` 

我刚才完整安装一遍发现也就要不到1分钟， 可能我机器上东西都比较全

**Comment by lococo--0** [comment]
恩，主要公司网络太慢，这样多的依赖有点奢侈，我自己写了个

**Comment by fisker** [comment]
seperated packages released

https://www.npmjs.com/browse/keyword/fis3-optimizer-imagemin
